# -*- coding: utf-8 -*-
"""Face Detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PP8Caj_lPt0ZIa6eHqCCiPZNWR74xMXv
"""

!pip install opencv-python

!wget https://github.com/opencv/opencv/raw/master/data/haarcascades/haarcascade_frontalface_default.xml

from google.colab import files
uploaded = files.upload()

import cv2
from google.colab.patches import cv2_imshow

# Load the face detection model
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Read the uploaded image
image_path = list(uploaded.keys())[0]
img = cv2.imread(image_path)

# Convert image to grayscale (Haar cascade works on gray images)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Detect faces
faces = face_cascade.detectMultiScale(gray, scaleFactor=1.3, minNeighbors=5)

# Draw rectangles around faces
for (x, y, w, h) in faces:
    cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)

# Show the result
cv2_imshow(img)
print(f"Number of faces detected: {len(faces)}")